using TonightsTheNight.Util;

namespace TonightsTheNight.Config
{
    /// <summary>
    /// The shipped defaults layer, written to defaults.json on every version change.
    ///
    /// This file describes what actually works in the current build — settings for unbuilt
    /// features are deliberately absent rather than present and inert, so the config never
    /// promises a knob that does nothing.
    /// </summary>
    public static class DefaultConfig
    {
        public const string Version = "0.6.0";

        public static JsonValue Build()
        {
            JsonValue root = JsonValue.NewObject();
            root.Set("version", JsonValue.Of(Version));
            root.Set("_readme", JsonValue.Of(
                "Do not edit this file - it is overwritten on update. Copy any key you want to " +
                "change into user.json, which is never touched. Comments and trailing commas are allowed."));

            JsonValue menu = JsonValue.NewObject();
            menu.Set("key", JsonValue.Of("F6"));
            menu.Set("reloadKey", JsonValue.Of("F5"));
            // Drops the parts of the menu that cost the most to draw: the instructional buttons
            // in the corner (a Scaleform, redrawn every frame), the banner texture, mouse
            // support and edge-of-screen camera rotation. The menu keeps its title, items and
            // descriptions. Set false if you would rather have the banner and mouse back.
            menu.Set("lightweight", JsonValue.Of(true));
            root.Set("menu", menu);

            JsonValue logging = JsonValue.NewObject();
            logging.Set("level", JsonValue.Of("Info"));   // Debug | Info | Warn | Error
            root.Set("logging", logging);

            // Budget-first: these are the numbers that decide whether the mod runs or hitches.
            JsonValue engine = JsonValue.NewObject();
            engine.Set("pedsPerTick", JsonValue.Of(12));
            // The script itself ticks every frame; this throttles only recruiting and retasking.
            engine.Set("workIntervalMs", JsonValue.Of(50));
            engine.Set("cullDistance", JsonValue.Of(450));
            engine.Set("maxTrackedPeds", JsonValue.Of(120));
            engine.Set("adaptiveBudget", JsonValue.Of(true));
            engine.Set("targetTickMs", JsonValue.Of(1.5));
            root.Set("engine", engine);

            JsonValue riot = JsonValue.NewObject();
            riot.Set("convertAmbientPeds", JsonValue.Of(true));
            // Roughly half the nearby crowd joins a faction. The other half is left completely
            // alone rather than converted into fleeing bystanders: an untouched ped walking
            // normally reads far better than a converted one running, and a street where
            // everyone flees looks as wrong as one where everyone fights.
            riot.Set("conversionChance", JsonValue.Of(0.55));
            riot.Set("recruitRadius", JsonValue.Of(180));
            riot.Set("groupVehicleOccupants", JsonValue.Of(true));
            riot.Set("restoreWorldOnStop", JsonValue.Of(true));
            // Peds who wounded each other re-engage from vanilla AI memory after one task
            // clear, so keep calming them for a few seconds after a stop.
            riot.Set("pacifySeconds", JsonValue.Of(5));
            riot.Set("spawnFactions", JsonValue.Of(true));
            root.Set("riot", riot);

            // Ped density is a per-frame native, so these are applied every tick while active.
            JsonValue density = JsonValue.NewObject();
            density.Set("enabled", JsonValue.Of(true));
            // A riot consumes its own participants. Without extra crowd the local population
            // is spent in a couple of minutes and the street goes quiet. Needs a gameconfig and
            // Heap Adjuster to be safe at this level - see INSTALL.md.
            density.Set("pedMultiplier", JsonValue.Of(2.5));
            density.Set("vehicleMultiplier", JsonValue.Of(0.8));
            density.Set("scenarioMultiplier", JsonValue.Of(0.4));
            root.Set("density", density);

            JsonValue combat = JsonValue.NewObject();
            combat.Set("alwaysFight", JsonValue.Of(true));
            combat.Set("neverFlee", JsonValue.Of(true));
            combat.Set("canUseCover", JsonValue.Of(true));
            combat.Set("canFightArmedWhenUnarmed", JsonValue.Of(true));
            combat.Set("canUseVehicles", JsonValue.Of(false));
            combat.Set("accuracy", JsonValue.Of(20));        // 0-100
            combat.Set("combatAbility", JsonValue.Of(1));    // 0 poor, 1 average, 2 professional
            combat.Set("seeingRange", JsonValue.Of(60));
            combat.Set("hearingRange", JsonValue.Of(60));
            combat.Set("retaskIntervalMs", JsonValue.Of(6000));
            // Stops gunfire and screams pulling fighters out of combat and into a panic run.
            // Turning this off makes a riot scatter the moment the first shot is fired.
            combat.Set("blockPanicEvents", JsonValue.Of(true));

            // SET_PED_COMBAT_ATTRIBUTES IDs. These are community-documented rather than
            // official and are the most likely thing here to be quietly wrong, so they are
            // tunable: if rioters stand around doing nothing, try other values for alwaysFight
            // (46, 5, 1, 17) and reload with the reload key rather than waiting for a new build.
            JsonValue attributeIds = JsonValue.NewObject();
            attributeIds.Set("alwaysFight", JsonValue.Of(46));
            attributeIds.Set("canUseCover", JsonValue.Of(0));
            attributeIds.Set("canUseVehicles", JsonValue.Of(1));
            attributeIds.Set("canDoDrivebys", JsonValue.Of(2));
            attributeIds.Set("canLeaveVehicle", JsonValue.Of(3));
            attributeIds.Set("canFightArmedWhenUnarmed", JsonValue.Of(5));
            combat.Set("attributeIds", attributeIds);

            root.Set("combat", combat);

            // Weapon presets. "mode" leaves each mode's own loadouts alone and is the default,
            // because a mode author balanced theirs and a preset cannot know that. The others
            // replace the loadout of the factions drawn from the ambient crowd only - a preset
            // answers "what is the mob carrying", not "how is the army equipped".
            JsonValue weapons = JsonValue.NewObject();
            weapons.Set("preset", JsonValue.Of("mode"));   // mode | realistic | armed | military | chaos | custom
            // Used when preset is "custom". Bare names or {"name": ..., "weight": ...}.
            weapons.Set("custom", JsonValue.NewArray());
            weapons.Set("customArmedChance", JsonValue.Of(1.0));
            weapons.Set("customArmour", JsonValue.Of(0));
            weapons.Set("customAmmo", JsonValue.Of(120));
            root.Set("weapons", weapons);

            // What a rioter already behind a wheel does about it.
            //
            // These weights exist because the obvious answer is wrong: tasking every driver to
            // fight made all of them stop in the road and get out, so driving past a riot gave
            // you a street of abandoned cars and people walking at you - every driver making the
            // identical decision, which reads as a scripted trap rather than as a city coming
            // apart. Rebalance freely; only the mix matters, not the totals.
            JsonValue vehicles = JsonValue.NewObject();
            vehicles.Set("enabled", JsonValue.Of(true));
            vehicles.Set("dismountWeight", JsonValue.Of(3));      // stop, get out, fight
            vehicles.Set("huntEnemyWeight", JsonValue.Of(3));     // go after another rioter
            vehicles.Set("huntPlayerWeight", JsonValue.Of(2));    // come after you
            vehicles.Set("fleePlayerWeight", JsonValue.Of(2));    // get away from you
            vehicles.Set("driveBys", JsonValue.Of(true));
            vehicles.Set("driveByRange", JsonValue.Of(60));
            vehicles.Set("driveByAccuracy", JsonValue.Of(35));
            vehicles.Set("driveThroughCrowds", JsonValue.Of(true));
            vehicles.Set("ram", JsonValue.Of(false));
            // Community-documented native values, so they are here rather than compiled in.
            vehicles.Set("ramMission", JsonValue.Of(6));
            vehicles.Set("fleeMission", JsonValue.Of(8));
            // Flags for IS_PED_ARMED. If nobody shoots from a car, or the man with the golf
            // club does, this is the value to change.
            vehicles.Set("armedCheckFlags", JsonValue.Of(4));
            vehicles.Set("chaseSpeed", JsonValue.Of(55));
            vehicles.Set("fleeSpeed", JsonValue.Of(45));
            vehicles.Set("aggressiveness", JsonValue.Of(0.9));
            vehicles.Set("driverAbility", JsonValue.Of(0.8));
            vehicles.Set("drivingStyle", JsonValue.Of(786603));
            root.Set("vehicles", vehicles);

            JsonValue blips = JsonValue.NewObject();
            blips.Set("enabled", JsonValue.Of(true));
            blips.Set("maxBlips", JsonValue.Of(40));
            blips.Set("maxDistance", JsonValue.Of(200));
            blips.Set("scale", JsonValue.Of(0.6));
            blips.Set("showOnlyWhenNear", JsonValue.Of(true));
            root.Set("blips", blips);

            JsonValue player = JsonValue.NewObject();
            player.Set("side", JsonValue.Of("neutral"));       // neutral | <faction id>
            // mode | ignored | disliked | target. "mode" lets each faction answer for itself,
            // which is the only way Martial Law works: the army should want you and the crowd
            // being shot at should not. The other three force one answer on every faction.
            player.Set("stance", JsonValue.Of("mode"));
            root.Set("player", player);

            // Where the riot is. Confining it is both the cheapest performance control and the
            // thing that produces the best scenes - one district in flames beats uniform chaos.
            JsonValue zone = JsonValue.NewObject();
            zone.Set("mode", JsonValue.Of("radius"));     // radius | citywide
            zone.Set("radius", JsonValue.Of(300));
            zone.Set("followPlayer", JsonValue.Of(true));
            // Off: with the zone following you, a circle centred on your own blip tells you
            // nothing. Turn it on if you anchor the riot somewhere and drive away from it.
            zone.Set("showOnMap", JsonValue.Of(false));
            root.Set("zone", zone);

            // Compatibility with other mods. These default to the conservative choice: this
            // mod stays out of systems another mod might own.
            JsonValue compatibility = JsonValue.NewObject();
            compatibility.Set("protectEmergencyServices", JsonValue.Of(true));
            compatibility.Set("protectMissionPeds", JsonValue.Of(true));
            // Off by default and expected to stay off. Police/wanted overhauls (OIV packs,
            // LSPDFR-style mods, 6-star replacements) own the wanted system; riot police are
            // built from relationship groups instead, so the two never collide.
            compatibility.Set("manageWantedSystem", JsonValue.Of(false));
            root.Set("compatibility", compatibility);

            // Feature flags. Every extra is optional AND customisable: a switch plus a block.
            JsonValue features = JsonValue.NewObject();

            JsonValue hotReload = JsonValue.NewObject();
            hotReload.Set("enabled", JsonValue.Of(true));
            hotReload.Set("watchFiles", JsonValue.Of(true));
            hotReload.Set("watchIntervalMs", JsonValue.Of(2000));
            hotReload.Set("restartModeOnReload", JsonValue.Of(false));
            features.Set("hotReload", hotReload);

            JsonValue overlay = JsonValue.NewObject();
            overlay.Set("enabled", JsonValue.Of(false));
            overlay.Set("showPerformance", JsonValue.Of(true));
            overlay.Set("showCounts", JsonValue.Of(true));
            overlay.Set("showFactions", JsonValue.Of(true));
            overlay.Set("x", JsonValue.Of(0.015));
            overlay.Set("y", JsonValue.Of(0.28));
            overlay.Set("scale", JsonValue.Of(0.32));
            features.Set("debugOverlay", overlay);

            JsonValue escalation = JsonValue.NewObject();
            escalation.Set("enabled", JsonValue.Of(true));
            features.Set("escalation", escalation);

            // Off by default, and the shipped modes no longer ask for any of it. A riot mod
            // that changes your weather and time of day is a mod that has taken over the
            // screen; if you want the look, these are here and each mode can declare its own.
            JsonValue ambience = JsonValue.NewObject();
            ambience.Set("enabled", JsonValue.Of(false));
            ambience.Set("setWeather", JsonValue.Of(true));
            // Even with ambience on, the clock is left alone unless you ask.
            ambience.Set("setTime", JsonValue.Of(false));
            ambience.Set("setTimecycle", JsonValue.Of(true));
            features.Set("ambience", ambience);

            JsonValue fires = JsonValue.NewObject();
            fires.Set("enabled", JsonValue.Of(true));
            fires.Set("maxActive", JsonValue.Of(8));
            fires.Set("intervalMs", JsonValue.Of(9000));
            fires.Set("radius", JsonValue.Of(120));
            fires.Set("size", JsonValue.Of(20));
            fires.Set("burnVehicles", JsonValue.Of(true));
            features.Set("fires", fires);

            JsonValue purge = JsonValue.NewObject();
            purge.Set("enabled", JsonValue.Of(true));
            purge.Set("startHour", JsonValue.Of(22));
            purge.Set("durationMinutes", JsonValue.Of(12));
            purge.Set("setClock", JsonValue.Of(false));
            // All crime is legal, so the game's own police should not be interested. Lowers the
            // wanted ceiling for the window and puts back whatever it was - a six-star overhaul
            // gets its six back the moment the purge ends.
            purge.Set("noWantedLevel", JsonValue.Of(true));
            features.Set("purge", purge);

            // Driving behaviour for police and military. The mission type and driving style are
            // community-documented rather than official, so they are tunable without a rebuild.
            JsonValue police = JsonValue.NewObject();
            police.Set("driveThroughCrowds", JsonValue.Of(true));
            police.Set("aggressiveness", JsonValue.Of(1.0));
            police.Set("driverAbility", JsonValue.Of(1.0));
            police.Set("muteSirens", JsonValue.Of(false));
            police.Set("vehicleMission", JsonValue.Of(6));       // 6 = ram
            police.Set("drivingStyle", JsonValue.Of(786603));
            police.Set("cruiseSpeed", JsonValue.Of(45));
            police.Set("targetReachedDistance", JsonValue.Of(5));
            police.Set("straightLineDistance", JsonValue.Of(8));
            features.Set("police", police);

            // Helicopters. TASK_HELI_MISSION is community-documented rather than official, so
            // if air support parks on a rooftop instead of holding station, these are the knobs.
            JsonValue air = JsonValue.NewObject();
            air.Set("heliMission", JsonValue.Of(4));
            air.Set("speed", JsonValue.Of(40));
            air.Set("radius", JsonValue.Of(60));
            air.Set("maxHeight", JsonValue.Of(90));
            air.Set("minHeight", JsonValue.Of(35));
            // Jets. They stay high: a fighter told to attack a street mostly flies into a
            // building, so the default mission circles at altitude instead.
            air.Set("planeMission", JsonValue.Of(6));
            air.Set("planeSpeed", JsonValue.Of(90));
            air.Set("planeHeading", JsonValue.Of(-1));
            air.Set("planeMaxHeight", JsonValue.Of(260));
            air.Set("planeMinHeight", JsonValue.Of(160));
            features.Set("air", air);

            // Car chases. Provocation-driven: hurt someone and drive away, and their side
            // comes after you in a carload. Never touches the wanted system, so this can run
            // alongside a police or wanted overhaul without either noticing the other.
            JsonValue pursuit = JsonValue.NewObject();
            pursuit.Set("enabled", JsonValue.Of(true));
            // How long after you hurt someone their faction still wants to chase you.
            pursuit.Set("grudgeSeconds", JsonValue.Of(45));
            pursuit.Set("maxChases", JsonValue.Of(2));
            pursuit.Set("crewSize", JsonValue.Of(3));
            // "Tries to drive off" is the trigger, in metres per second. Sitting still in a
            // car should get you dragged out of it, not tailed.
            pursuit.Set("minPlayerSpeed", JsonValue.Of(6));
            pursuit.Set("formRadius", JsonValue.Of(120));
            pursuit.Set("gatherRadius", JsonValue.Of(35));
            pursuit.Set("vehicleSearchRadius", JsonValue.Of(45));
            // How long the crew gets to reach the car on foot before they are warped in. A
            // chase that never leaves the kerb is worse than one that starts a bit too neatly.
            pursuit.Set("boardTimeoutMs", JsonValue.Of(7000));
            pursuit.Set("cooldownMs", JsonValue.Of(12000));
            pursuit.Set("updateIntervalMs", JsonValue.Of(500));
            pursuit.Set("retaskMs", JsonValue.Of(5000));
            pursuit.Set("giveUpDistance", JsonValue.Of(320));
            pursuit.Set("giveUpSeconds", JsonValue.Of(12));
            pursuit.Set("maxSeconds", JsonValue.Of(150));
            pursuit.Set("driveBys", JsonValue.Of(true));
            pursuit.Set("driveByRange", JsonValue.Of(60));
            pursuit.Set("driveByAccuracy", JsonValue.Of(40));
            // Off: they tail you and shoot. On: they drive into you instead.
            pursuit.Set("ram", JsonValue.Of(false));
            pursuit.Set("aggressiveness", JsonValue.Of(1.0));
            pursuit.Set("driverAbility", JsonValue.Of(1.0));
            pursuit.Set("cruiseSpeed", JsonValue.Of(60));
            pursuit.Set("drivingStyle", JsonValue.Of(786603));
            pursuit.Set("blip", JsonValue.Of(true));
            pursuit.Set("notify", JsonValue.Of(true));
            features.Set("pursuit", pursuit);

            // Looting. Gated on the escalation phase, so it starts once the riot has been
            // going a while rather than in the first thirty seconds.
            JsonValue looting = JsonValue.NewObject();
            looting.Set("enabled", JsonValue.Of(true));
            looting.Set("maxActive", JsonValue.Of(6));
            looting.Set("intervalMs", JsonValue.Of(6000));
            looting.Set("radius", JsonValue.Of(90));
            looting.Set("jobSeconds", JsonValue.Of(40));
            looting.Set("runDistance", JsonValue.Of(70));
            looting.Set("carryProps", JsonValue.Of(true));
            // Fighters are busy. Looting is mostly what the people who were never going to
            // fight do instead, which is also what stops it thinning out the riot.
            looting.Set("fighterChance", JsonValue.Of(0.2));
            looting.Set("stealVehicles", JsonValue.Of(true));
            looting.Set("vehicleChance", JsonValue.Of(0.25));
            looting.Set("vehicleSearchRadius", JsonValue.Of(30));
            looting.Set("getawaySpeed", JsonValue.Of(25));
            looting.Set("drivingStyle", JsonValue.Of(786603));
            features.Set("looting", looting);

            // A faction that is losing sends more. Escalation phases answer "how long has this
            // been going on"; this answers "how badly is it going", which is the difference
            // between a deployment and a response.
            JsonValue reinforcements = JsonValue.NewObject();
            reinforcements.Set("enabled", JsonValue.Of(true));
            // Each spawned member killed adds this much to that faction's wave size, cap and
            // arrival rate. Sixteen losses reaches the ceiling at the default values.
            reinforcements.Set("perLoss", JsonValue.Of(0.06));
            reinforcements.Set("maxMultiplier", JsonValue.Of(2.5));
            reinforcements.Set("announce", JsonValue.Of(true));
            features.Set("reinforcements", reinforcements);

            // Ships in the sky. Props rather than vehicles, because GTA V's UFOs are props -
            // there is nothing to fly and nobody to put in one - so they are held at altitude
            // and drifted. A mode declares its own; only the invasion has any.
            JsonValue craft = JsonValue.NewObject();
            craft.Set("enabled", JsonValue.Of(true));
            craft.Set("maxActive", JsonValue.Of(4));
            craft.Set("orbitSpeed", JsonValue.Of(0.06));
            craft.Set("updateIntervalMs", JsonValue.Of(250));
            craft.Set("dropScatter", JsonValue.Of(20));
            craft.Set("blip", JsonValue.Of(true));
            features.Set("craft", craft);

            // Whether the riot knows where you are.
            //
            // Off, hostility is a permanent property of a relationship group: every soldier in
            // the district is your enemy from the moment the mode starts, through walls and
            // around corners. On, being a target is a state you can get out of - break line of
            // sight, stay quiet, and they go back to fighting the people they can see.
            JsonValue perception = JsonValue.NewObject();
            perception.Set("enabled", JsonValue.Of(true));
            perception.Set("sightRange", JsonValue.Of(60));
            // How long they keep looking after losing sight of you.
            perception.Set("forgetSeconds", JsonValue.Of(12));
            perception.Set("checkIntervalMs", JsonValue.Of(400));
            // Line-of-sight traces are the expensive part, so only this many per check. The
            // round-robin covers the whole crowd over a couple of seconds anyway.
            perception.Set("samplesPerCheck", JsonValue.Of(6));
            // Firing a weapon gives you away through walls, as it should.
            perception.Set("gunfireGivesYouAway", JsonValue.Of(true));
            // Crouching or taking cover multiplies their sight range by this.
            perception.Set("stealthFactor", JsonValue.Of(0.45));
            // On, a ped must be facing you to see you. Off by default: people have peripheral
            // vision, and a hard cone reads as the AI being broken rather than as stealth.
            perception.Set("requireFacing", JsonValue.Of(false));
            perception.Set("notify", JsonValue.Of(true));
            features.Set("perception", perception);

            JsonValue profiles = JsonValue.NewObject();
            profiles.Set("enabled", JsonValue.Of(true));
            profiles.Set("autoload", JsonValue.Of(""));
            features.Set("profiles", profiles);

            root.Set("features", features);
            return root;
        }
    }
}
