using TonightsTheNight.Util;

namespace TonightsTheNight.Config
{
    /// <summary>
    /// The shipped defaults layer, written to defaults.json on every version change.
    ///
    /// This file describes what actually works in the current build — settings for unbuilt
    /// features are deliberately absent rather than present and inert, so the config never
    /// promises a knob that does nothing.
    /// </summary>
    public static class DefaultConfig
    {
        public const string Version = "0.1.0";

        public static JsonValue Build()
        {
            JsonValue root = JsonValue.NewObject();
            root.Set("version", JsonValue.Of(Version));
            root.Set("_readme", JsonValue.Of(
                "Do not edit this file - it is overwritten on update. Copy any key you want to " +
                "change into user.json, which is never touched. Comments and trailing commas are allowed."));

            JsonValue menu = JsonValue.NewObject();
            menu.Set("key", JsonValue.Of("F6"));
            menu.Set("reloadKey", JsonValue.Of("F5"));
            root.Set("menu", menu);

            JsonValue logging = JsonValue.NewObject();
            logging.Set("level", JsonValue.Of("Info"));   // Debug | Info | Warn | Error
            root.Set("logging", logging);

            // Budget-first: these are the numbers that decide whether the mod runs or hitches.
            JsonValue engine = JsonValue.NewObject();
            engine.Set("pedsPerTick", JsonValue.Of(12));
            // The script itself ticks every frame; this throttles only recruiting and retasking.
            engine.Set("workIntervalMs", JsonValue.Of(50));
            engine.Set("cullDistance", JsonValue.Of(450));
            engine.Set("maxTrackedPeds", JsonValue.Of(120));
            engine.Set("adaptiveBudget", JsonValue.Of(true));
            engine.Set("targetTickMs", JsonValue.Of(1.5));
            root.Set("engine", engine);

            JsonValue riot = JsonValue.NewObject();
            riot.Set("convertAmbientPeds", JsonValue.Of(true));
            // Most people should not be in a faction. A crowd where everyone is fighting reads
            // as "everyone simultaneously decided to brawl"; a minority fighting while the rest
            // react reads as a riot.
            riot.Set("conversionChance", JsonValue.Of(0.35));
            riot.Set("recruitRadius", JsonValue.Of(180));
            riot.Set("groupVehicleOccupants", JsonValue.Of(true));
            riot.Set("restoreWorldOnStop", JsonValue.Of(true));
            root.Set("riot", riot);

            // Ped density is a per-frame native, so these are applied every tick while active.
            JsonValue density = JsonValue.NewObject();
            density.Set("enabled", JsonValue.Of(true));
            density.Set("pedMultiplier", JsonValue.Of(1.5));
            density.Set("vehicleMultiplier", JsonValue.Of(0.8));
            density.Set("scenarioMultiplier", JsonValue.Of(0.4));
            root.Set("density", density);

            JsonValue combat = JsonValue.NewObject();
            combat.Set("alwaysFight", JsonValue.Of(true));
            combat.Set("neverFlee", JsonValue.Of(true));
            combat.Set("canUseCover", JsonValue.Of(true));
            combat.Set("canFightArmedWhenUnarmed", JsonValue.Of(true));
            combat.Set("canUseVehicles", JsonValue.Of(false));
            combat.Set("accuracy", JsonValue.Of(20));        // 0-100
            combat.Set("combatAbility", JsonValue.Of(1));    // 0 poor, 1 average, 2 professional
            combat.Set("seeingRange", JsonValue.Of(60));
            combat.Set("hearingRange", JsonValue.Of(60));
            combat.Set("retaskIntervalMs", JsonValue.Of(6000));

            // SET_PED_COMBAT_ATTRIBUTES IDs. These are community-documented rather than
            // official and are the most likely thing here to be quietly wrong, so they are
            // tunable: if rioters stand around doing nothing, try other values for alwaysFight
            // (46, 5, 1, 17) and reload with the reload key rather than waiting for a new build.
            JsonValue attributeIds = JsonValue.NewObject();
            attributeIds.Set("alwaysFight", JsonValue.Of(46));
            attributeIds.Set("canUseCover", JsonValue.Of(0));
            attributeIds.Set("canUseVehicles", JsonValue.Of(1));
            attributeIds.Set("canDoDrivebys", JsonValue.Of(2));
            attributeIds.Set("canLeaveVehicle", JsonValue.Of(3));
            attributeIds.Set("canFightArmedWhenUnarmed", JsonValue.Of(5));
            combat.Set("attributeIds", attributeIds);

            root.Set("combat", combat);

            JsonValue blips = JsonValue.NewObject();
            blips.Set("enabled", JsonValue.Of(true));
            blips.Set("maxBlips", JsonValue.Of(40));
            blips.Set("maxDistance", JsonValue.Of(200));
            blips.Set("scale", JsonValue.Of(0.6));
            blips.Set("showOnlyWhenNear", JsonValue.Of(true));
            root.Set("blips", blips);

            JsonValue player = JsonValue.NewObject();
            player.Set("side", JsonValue.Of("neutral"));       // neutral | <faction id>
            player.Set("everyoneHatesPlayer", JsonValue.Of(false));
            root.Set("player", player);

            // Compatibility with other mods. These default to the conservative choice: this
            // mod stays out of systems another mod might own.
            JsonValue compatibility = JsonValue.NewObject();
            compatibility.Set("protectEmergencyServices", JsonValue.Of(true));
            compatibility.Set("protectMissionPeds", JsonValue.Of(true));
            // Off by default and expected to stay off. Police/wanted overhauls (OIV packs,
            // LSPDFR-style mods, 6-star replacements) own the wanted system; riot police are
            // built from relationship groups instead, so the two never collide.
            compatibility.Set("manageWantedSystem", JsonValue.Of(false));
            root.Set("compatibility", compatibility);

            // Feature flags. Every extra is optional AND customisable: a switch plus a block.
            JsonValue features = JsonValue.NewObject();

            JsonValue hotReload = JsonValue.NewObject();
            hotReload.Set("enabled", JsonValue.Of(true));
            hotReload.Set("watchFiles", JsonValue.Of(true));
            hotReload.Set("watchIntervalMs", JsonValue.Of(2000));
            hotReload.Set("restartModeOnReload", JsonValue.Of(false));
            features.Set("hotReload", hotReload);

            JsonValue overlay = JsonValue.NewObject();
            overlay.Set("enabled", JsonValue.Of(false));
            overlay.Set("showPerformance", JsonValue.Of(true));
            overlay.Set("showCounts", JsonValue.Of(true));
            overlay.Set("showFactions", JsonValue.Of(true));
            overlay.Set("x", JsonValue.Of(0.015));
            overlay.Set("y", JsonValue.Of(0.28));
            overlay.Set("scale", JsonValue.Of(0.32));
            features.Set("debugOverlay", overlay);

            root.Set("features", features);
            return root;
        }
    }
}
