using TonightsTheNight.Util;

namespace TonightsTheNight.Config
{
    /// <summary>
    /// The shipped defaults layer, written to defaults.json on every version change.
    ///
    /// This file describes what actually works in the current build — settings for unbuilt
    /// features are deliberately absent rather than present and inert, so the config never
    /// promises a knob that does nothing.
    /// </summary>
    public static class DefaultConfig
    {
        public const string Version = "1.0.0";

        /// <summary>
        /// The shipped carryable props. Mirrored by <c>CarryProps.Fallback</c> so the feature
        /// survives a broken config; a test keeps the two in step.
        /// </summary>
        private static JsonValue CarryPropDefaults()
        {
            JsonValue list = JsonValue.NewArray();

            AddCarryProp(list, "prop_ld_case_01",      "hand", 0.13, 0.02, -0.02, 0, 0, -100);
            AddCarryProp(list, "prop_cash_case_01",    "hand", 0.13, 0.02, -0.02, 0, 0, -100);
            AddCarryProp(list, "prop_paper_bag_01",    "hand", 0.10, 0.01, -0.05, 10, 0, -95);
            AddCarryProp(list, "prop_big_bag_01",      "hand", 0.14, 0.02, -0.08, 5, 0, -100);
            AddCarryProp(list, "prop_binbag_01",       "hand", 0.12, 0.01, -0.10, 0, 0, -95);
            AddCarryProp(list, "prop_cs_shopping_bag", "hand", 0.10, 0.01, -0.06, 5, 0, -95);
            AddCarryProp(list, "prop_tv_flat_01",      "box",  0.025, 0.12, 0.24, -145, 290, 0);
            AddCarryProp(list, "prop_cs_box_clothes",  "box",  0.025, 0.08, 0.255, -145, 290, 0);
            AddCarryProp(list, "prop_cs_cardbox_01",   "box",  0.025, 0.08, 0.255, -145, 290, 0);
            AddCarryProp(list, "prop_boxpile_07d",     "box",  0.025, 0.08, 0.255, -145, 290, 0);

            return list;
        }

        private static void AddCarryProp(JsonValue list, string model, string style,
                                         double x, double y, double z, double rx, double ry, double rz)
        {
            JsonValue entry = JsonValue.NewObject();
            entry.Set("model", JsonValue.Of(model));
            entry.Set("style", JsonValue.Of(style));
            entry.Set("x", JsonValue.Of(x));
            entry.Set("y", JsonValue.Of(y));
            entry.Set("z", JsonValue.Of(z));
            entry.Set("rx", JsonValue.Of(rx));
            entry.Set("ry", JsonValue.Of(ry));
            entry.Set("rz", JsonValue.Of(rz));
            list.Add(entry);
        }

        public static JsonValue Build()
        {
            JsonValue root = JsonValue.NewObject();
            root.Set("version", JsonValue.Of(Version));
            root.Set("_readme", JsonValue.Of(
                "Do not edit this file - it is overwritten on update. Copy any key you want to " +
                "change into user.json, which is never touched. Comments and trailing commas are allowed."));

            JsonValue menu = JsonValue.NewObject();
            menu.Set("key", JsonValue.Of("F6"));
            menu.Set("reloadKey", JsonValue.Of("F5"));
            // Drops the parts of the menu that cost the most to draw: the instructional buttons
            // in the corner (a Scaleform, redrawn every frame), the banner texture, mouse
            // support and edge-of-screen camera rotation. The menu keeps its title, items and
            // descriptions. Set false if you would rather have the banner and mouse back.
            // Off. Stripping the banner and the corner Scaleform was tried as a frame-rate fix
            // and did not work, so the decoration is back; this is here for anyone who wants the
            // plainest possible menu regardless.
            menu.Set("lightweight", JsonValue.Of(false));
            // texture | flat | none.
            //
            // The texture is a base-game asset, tinted. A flat rectangle was the original and is
            // the reason the header used to be the game showing through with a title floating
            // over it: there is nothing behind a rectangle until LemonUI has sized it.
            menu.Set("bannerStyle", JsonValue.Of("texture"));
            // "r,g,b" or "a,r,g,b".
            menu.Set("bannerColour", JsonValue.Of("235,132,22,22"));
            menu.Set("titleColour", JsonValue.Of("255,255,255,255"));
            // Any GTA.UI.Font name. HouseScript - the handwritten one - is the reason the title
            // used to lie across the first two items: its glyphs are far taller than the Chalet
            // faces LemonUI sizes the header against.
            menu.Set("titleFont", JsonValue.Of("ChaletComprimeCologne"));
            // Clamped to 0.4-1.2 in code. A title that overhangs the items should not be
            // reachable by typing a number into a file.
            menu.Set("titleScale", JsonValue.Of(0.95));
            menu.Set("maxItems", JsonValue.Of(9));
            menu.Set("width", JsonValue.Of(460));
            root.Set("menu", menu);

            JsonValue logging = JsonValue.NewObject();
            logging.Set("level", JsonValue.Of("Info"));   // Debug | Info | Warn | Error
            root.Set("logging", logging);

            // Budget-first: these are the numbers that decide whether the mod runs or hitches.
            JsonValue engine = JsonValue.NewObject();
            engine.Set("pedsPerTick", JsonValue.Of(12));
            // The script itself ticks every frame; this throttles only recruiting and retasking.
            engine.Set("workIntervalMs", JsonValue.Of(50));
            engine.Set("cullDistance", JsonValue.Of(450));
            engine.Set("maxTrackedPeds", JsonValue.Of(120));
            // Vehicles this mod owns. They are mission entities while we hold them, so something
            // has to decide when to let go or they stay pinned for the session.
            engine.Set("maxTrackedVehicles", JsonValue.Of(40));
            // An empty one this far away has served its purpose - the crew got out or died.
            engine.Set("abandonedVehicleDistance", JsonValue.Of(120));
            engine.Set("adaptiveBudget", JsonValue.Of(true));
            engine.Set("targetTickMs", JsonValue.Of(1.5));
            root.Set("engine", engine);

            JsonValue riot = JsonValue.NewObject();
            riot.Set("convertAmbientPeds", JsonValue.Of(true));
            // Roughly half the nearby crowd joins a faction. The other half is left completely
            // alone rather than converted into fleeing bystanders: an untouched ped walking
            // normally reads far better than a converted one running, and a street where
            // everyone flees looks as wrong as one where everyone fights.
            riot.Set("conversionChance", JsonValue.Of(0.55));
            riot.Set("recruitRadius", JsonValue.Of(180));
            riot.Set("groupVehicleOccupants", JsonValue.Of(true));
            riot.Set("restoreWorldOnStop", JsonValue.Of(true));
            // Peds who wounded each other re-engage from vanilla AI memory after one task
            // clear, so keep calming them for a few seconds after a stop.
            riot.Set("pacifySeconds", JsonValue.Of(5));
            riot.Set("spawnFactions", JsonValue.Of(true));
            // One number for "how much of this do I want". Multiplies every spawning faction's
            // wave size and ceiling and divides the gap between its waves, so the whole mod can
            // be turned down without editing nine mode files - or turned up past what any of
            // them were balanced for, which is a choice rather than an accident.
            riot.Set("intensity", JsonValue.Of(1.0));
            // A riot you died in is over. Off, it carries on through respawn, which is the
            // behaviour if you want the world to stay changed.
            riot.Set("stopOnPlayerDeath", JsonValue.Of(true));
            root.Set("riot", riot);

            // Ped density is a per-frame native, so these are applied every tick while active.
            JsonValue density = JsonValue.NewObject();
            density.Set("enabled", JsonValue.Of(true));
            // A riot consumes its own participants. Without extra crowd the local population
            // is spent in a couple of minutes and the street goes quiet. Needs a gameconfig and
            // Heap Adjuster to be safe at this level - see INSTALL.md.
            // 2.5 was set back when the riot consumed its own participants, before anything the
            // mod created was actually owned by it. Flooding the ambient pool while also
            // spawning is what left the engine reclaiming peds mid-fight, so this is lower now.
            density.Set("pedMultiplier", JsonValue.Of(1.8));
            // Above 1: traffic is scenery a riot needs. It is also what a chase commandeers and
            // what a looter steals, and 0.8 was thinning out both.
            density.Set("vehicleMultiplier", JsonValue.Of(1.3));
            density.Set("scenarioMultiplier", JsonValue.Of(0.4));
            root.Set("density", density);

            JsonValue combat = JsonValue.NewObject();
            combat.Set("alwaysFight", JsonValue.Of(true));
            combat.Set("neverFlee", JsonValue.Of(true));
            combat.Set("canUseCover", JsonValue.Of(true));
            combat.Set("canFightArmedWhenUnarmed", JsonValue.Of(true));
            combat.Set("canUseVehicles", JsonValue.Of(false));
            combat.Set("accuracy", JsonValue.Of(20));        // 0-100
            combat.Set("combatAbility", JsonValue.Of(1));    // 0 poor, 1 average, 2 professional
            combat.Set("seeingRange", JsonValue.Of(60));
            combat.Set("hearingRange", JsonValue.Of(60));
            combat.Set("retaskIntervalMs", JsonValue.Of(6000));
            // How many of them may be in a combat task against *you* at once.
            //
            // Hostility is a property of a relationship group, and a group has no size: the
            // moment the army could see you, every soldier in the district was individually
            // trying to kill you. This is the difference between an occupation you are caught in
            // and a firing squad. The rest carry on fighting whoever they were fighting, and
            // rotate back round to you later. 0 means no limit.
            combat.Set("maxPlayerAttackers", JsonValue.Of(4));
            combat.Set("attackerCheckMs", JsonValue.Of(1500));
            // How long somebody sent elsewhere is left alone before they may come back for you.
            combat.Set("attackerCooldownMs", JsonValue.Of(8000));
            // Rockets, launchers, miniguns and belt-fed machine guns, as a share of the picks
            // that landed on one. A weight of 1 against a 3 in a loadout means a quarter of the
            // faction, which by the last phase of Martial Law is a street nothing survives.
            // 1.0 honours every loadout exactly as written.
            combat.Set("heavyWeaponChance", JsonValue.Of(0.35));
            // Stops gunfire and screams pulling fighters out of combat and into a panic run.
            // Turning this off makes a riot scatter the moment the first shot is fired.
            combat.Set("blockPanicEvents", JsonValue.Of(true));

            // SET_PED_COMBAT_ATTRIBUTES IDs. These are community-documented rather than
            // official and are the most likely thing here to be quietly wrong, so they are
            // tunable: if rioters stand around doing nothing, try other values for alwaysFight
            // (46, 5, 1, 17) and reload with the reload key rather than waiting for a new build.
            JsonValue attributeIds = JsonValue.NewObject();
            attributeIds.Set("alwaysFight", JsonValue.Of(46));
            attributeIds.Set("canUseCover", JsonValue.Of(0));
            attributeIds.Set("canUseVehicles", JsonValue.Of(1));
            attributeIds.Set("canDoDrivebys", JsonValue.Of(2));
            attributeIds.Set("canLeaveVehicle", JsonValue.Of(3));
            attributeIds.Set("canFightArmedWhenUnarmed", JsonValue.Of(5));
            combat.Set("attributeIds", attributeIds);

            root.Set("combat", combat);

            // Weapon presets. "mode" leaves each mode's own loadouts alone and is the default,
            // because a mode author balanced theirs and a preset cannot know that. The others
            // replace the loadout of the factions drawn from the ambient crowd only - a preset
            // answers "what is the mob carrying", not "how is the army equipped".
            JsonValue weapons = JsonValue.NewObject();
            weapons.Set("preset", JsonValue.Of("mode"));   // mode | realistic | armed | military | chaos | custom
            // Used when preset is "custom". Bare names or {"name": ..., "weight": ...}.
            weapons.Set("custom", JsonValue.NewArray());
            weapons.Set("customArmedChance", JsonValue.Of(1.0));
            weapons.Set("customArmour", JsonValue.Of(0));
            weapons.Set("customAmmo", JsonValue.Of(120));
            root.Set("weapons", weapons);

            // What a rioter already behind a wheel does about it.
            //
            // These weights exist because the obvious answer is wrong: tasking every driver to
            // fight made all of them stop in the road and get out, so driving past a riot gave
            // you a street of abandoned cars and people walking at you - every driver making the
            // identical decision, which reads as a scripted trap rather than as a city coming
            // apart. Rebalance freely; only the mix matters, not the totals.
            JsonValue vehicles = JsonValue.NewObject();
            vehicles.Set("enabled", JsonValue.Of(true));
            vehicles.Set("dismountWeight", JsonValue.Of(3));      // stop, get out, fight
            vehicles.Set("huntEnemyWeight", JsonValue.Of(3));     // go after another rioter
            vehicles.Set("huntPlayerWeight", JsonValue.Of(2));    // come after you
            vehicles.Set("fleePlayerWeight", JsonValue.Of(2));    // get away from you
            vehicles.Set("driveBys", JsonValue.Of(true));
            vehicles.Set("driveByRange", JsonValue.Of(60));
            vehicles.Set("driveByAccuracy", JsonValue.Of(35));
            vehicles.Set("driveThroughCrowds", JsonValue.Of(true));
            vehicles.Set("ram", JsonValue.Of(false));
            // Community-documented native values, so they are here rather than compiled in.
            vehicles.Set("ramMission", JsonValue.Of(6));
            vehicles.Set("fleeMission", JsonValue.Of(8));
            // Flags for IS_PED_ARMED. If nobody shoots from a car, or the man with the golf
            // club does, this is the value to change.
            vehicles.Set("armedCheckFlags", JsonValue.Of(4));
            vehicles.Set("chaseSpeed", JsonValue.Of(55));
            vehicles.Set("fleeSpeed", JsonValue.Of(45));
            vehicles.Set("aggressiveness", JsonValue.Of(0.9));
            vehicles.Set("driverAbility", JsonValue.Of(0.8));
            vehicles.Set("drivingStyle", JsonValue.Of(786603));
            // How many drivers may be coming after you at once. The weights above are a
            // per-driver decision and say nothing about how many drivers have already made it,
            // so every car on the street rolling independently is how you end up being converged
            // on from four directions - which reads as the traffic being out to get you rather
            // than as a riot.
            vehicles.Set("maxHuntingPlayer", JsonValue.Of(1));
            vehicles.Set("huntPlayerHoldMs", JsonValue.Of(20000));
            // What a driver who is after you actually does. 7 is follow; 6 is attack, which
            // against somebody on foot is resolved with the bumper. Turn on vehicles.ram if
            // being driven into is the point.
            vehicles.Set("playerMission", JsonValue.Of(7));
            vehicles.Set("playerStandoff", JsonValue.Of(12));
            root.Set("vehicles", vehicles);

            // How arrivals are placed. Modelled on the game's own dispatch: on a road, facing
            // along it, out of your view, and far enough out that they drive in rather than
            // materialise in front of you.
            JsonValue spawn = JsonValue.NewObject();
            spawn.Set("offscreenOnly", JsonValue.Of(true));
            // Radius of the sphere tested against the camera. Bigger is stricter.
            spawn.Set("visibilityRadius", JsonValue.Of(4));
            // Points tried before settling for a visible one. Somewhere visible beats nowhere.
            spawn.Set("attempts", JsonValue.Of(14));
            // Applied to the distance when a faction that normally drives has to walk in.
            spawn.Set("footDistanceFactor", JsonValue.Of(0.45));
            root.Set("spawn", spawn);

            JsonValue blips = JsonValue.NewObject();
            blips.Set("enabled", JsonValue.Of(true));
            blips.Set("maxBlips", JsonValue.Of(40));
            blips.Set("maxDistance", JsonValue.Of(200));
            blips.Set("scale", JsonValue.Of(0.6));
            blips.Set("showOnlyWhenNear", JsonValue.Of(true));
            root.Set("blips", blips);

            JsonValue player = JsonValue.NewObject();
            player.Set("side", JsonValue.Of("neutral"));       // neutral | <faction id>
            // mode | ignored | disliked | target. "mode" lets each faction answer for itself,
            // which is the only way Martial Law works: the army should want you and the crowd
            // being shot at should not. The other three force one answer on every faction.
            player.Set("stance", JsonValue.Of("mode"));
            root.Set("player", player);

            // Where the riot is. Confining it is both the cheapest performance control and the
            // thing that produces the best scenes - one district in flames beats uniform chaos.
            JsonValue zone = JsonValue.NewObject();
            zone.Set("mode", JsonValue.Of("radius"));     // radius | citywide
            zone.Set("radius", JsonValue.Of(300));
            zone.Set("followPlayer", JsonValue.Of(true));
            // Off: with the zone following you, a circle centred on your own blip tells you
            // nothing. Turn it on if you anchor the riot somewhere and drive away from it.
            zone.Set("showOnMap", JsonValue.Of(false));
            root.Set("zone", zone);

            // Compatibility with other mods. These default to the conservative choice: this
            // mod stays out of systems another mod might own.
            JsonValue compatibility = JsonValue.NewObject();
            compatibility.Set("protectEmergencyServices", JsonValue.Of(true));
            compatibility.Set("protectMissionPeds", JsonValue.Of(true));
            // Off by default and expected to stay off. Police/wanted overhauls (OIV packs,
            // LSPDFR-style mods, 6-star replacements) own the wanted system; riot police are
            // built from relationship groups instead, so the two never collide.
            compatibility.Set("manageWantedSystem", JsonValue.Of(false));
            root.Set("compatibility", compatibility);

            // Feature flags. Every extra is optional AND customisable: a switch plus a block.
            JsonValue features = JsonValue.NewObject();

            JsonValue hotReload = JsonValue.NewObject();
            hotReload.Set("enabled", JsonValue.Of(true));
            hotReload.Set("watchFiles", JsonValue.Of(true));
            hotReload.Set("watchIntervalMs", JsonValue.Of(2000));
            hotReload.Set("restartModeOnReload", JsonValue.Of(false));
            features.Set("hotReload", hotReload);

            JsonValue overlay = JsonValue.NewObject();
            overlay.Set("enabled", JsonValue.Of(false));
            overlay.Set("showPerformance", JsonValue.Of(true));
            overlay.Set("showCounts", JsonValue.Of(true));
            overlay.Set("showFactions", JsonValue.Of(true));
            overlay.Set("x", JsonValue.Of(0.015));
            overlay.Set("y", JsonValue.Of(0.28));
            overlay.Set("scale", JsonValue.Of(0.32));
            features.Set("debugOverlay", overlay);

            JsonValue escalation = JsonValue.NewObject();
            escalation.Set("enabled", JsonValue.Of(true));
            features.Set("escalation", escalation);

            // Off by default, and the shipped modes no longer ask for any of it. A riot mod
            // that changes your weather and time of day is a mod that has taken over the
            // screen; if you want the look, these are here and each mode can declare its own.
            JsonValue ambience = JsonValue.NewObject();
            ambience.Set("enabled", JsonValue.Of(false));
            ambience.Set("setWeather", JsonValue.Of(true));
            // Even with ambience on, the clock is left alone unless you ask.
            ambience.Set("setTime", JsonValue.Of(false));
            ambience.Set("setTimecycle", JsonValue.Of(true));
            features.Set("ambience", ambience);

            JsonValue fires = JsonValue.NewObject();
            fires.Set("enabled", JsonValue.Of(true));
            fires.Set("maxActive", JsonValue.Of(8));
            fires.Set("intervalMs", JsonValue.Of(9000));
            fires.Set("radius", JsonValue.Of(120));
            fires.Set("size", JsonValue.Of(20));
            fires.Set("burnVehicles", JsonValue.Of(true));
            // How long a fire counts against maxActive. Script fires burn out on their own and
            // there is no native to ask whether one still is, so this is an estimate of how long
            // one lasts rather than a lifetime we enforce.
            fires.Set("lifetimeSeconds", JsonValue.Of(45));
            features.Set("fires", fires);

            JsonValue purge = JsonValue.NewObject();
            purge.Set("enabled", JsonValue.Of(true));
            purge.Set("startHour", JsonValue.Of(22));
            purge.Set("durationMinutes", JsonValue.Of(12));
            purge.Set("setClock", JsonValue.Of(false));
            // All crime is legal, so the game's own police should not be interested. Lowers the
            // wanted ceiling for the window and puts back whatever it was - a six-star overhaul
            // gets its six back the moment the purge ends.
            purge.Set("noWantedLevel", JsonValue.Of(true));
            // The countdown, on screen. The single most effective answer to "does this ever
            // end", which is a question the purge used to leave entirely to the log file.
            purge.Set("showTimer", JsonValue.Of(true));
            purge.Set("finalWarningSeconds", JsonValue.Of(60));
            // The siren, and the part where everybody has to stop. Nothing new arrives during
            // it and what is out there is talked down, so the event has an ending rather than
            // a cut.
            purge.Set("windDownSeconds", JsonValue.Of(25));
            features.Set("purge", purge);

            // Driving behaviour for police and military. The mission type and driving style are
            // community-documented rather than official, so they are tunable without a rebuild.
            JsonValue police = JsonValue.NewObject();
            police.Set("driveThroughCrowds", JsonValue.Of(true));
            police.Set("aggressiveness", JsonValue.Of(1.0));
            police.Set("driverAbility", JsonValue.Of(1.0));
            police.Set("muteSirens", JsonValue.Of(false));
            police.Set("vehicleMission", JsonValue.Of(6));       // 6 = attack
            // Used instead when the target is the player. 7 is follow: they pull up and get out
            // rather than resolving it with the front of the car.
            police.Set("playerVehicleMission", JsonValue.Of(7));
            police.Set("playerStandoff", JsonValue.Of(15));
            police.Set("drivingStyle", JsonValue.Of(786603));
            police.Set("cruiseSpeed", JsonValue.Of(45));
            police.Set("targetReachedDistance", JsonValue.Of(5));
            police.Set("straightLineDistance", JsonValue.Of(8));
            features.Set("police", police);

            // Helicopters. TASK_HELI_MISSION is community-documented rather than official, so
            // if air support parks on a rooftop instead of holding station, these are the knobs.
            JsonValue air = JsonValue.NewObject();
            air.Set("heliMission", JsonValue.Of(4));
            air.Set("speed", JsonValue.Of(40));
            air.Set("radius", JsonValue.Of(60));
            air.Set("maxHeight", JsonValue.Of(90));
            air.Set("minHeight", JsonValue.Of(35));
            // Jets. They stay high: a fighter told to attack a street mostly flies into a
            // building, so the default mission circles at altitude instead.
            air.Set("planeMission", JsonValue.Of(6));
            air.Set("planeSpeed", JsonValue.Of(90));
            air.Set("planeHeading", JsonValue.Of(-1));
            air.Set("planeMaxHeight", JsonValue.Of(260));
            air.Set("planeMinHeight", JsonValue.Of(160));
            air.Set("searchlight", JsonValue.Of(true));
            features.Set("air", air);

            // The city itself, rather than the people in it. A hundred people fighting on an
            // otherwise normal street still looks like a normal street; the power being out and
            // the roads being blocked is what reads as a riot from a rooftop.
            JsonValue spectacle = JsonValue.NewObject();
            spectacle.Set("blackout", JsonValue.Of(true));
            // never | phase | always. "phase" waits for a mode to ask for it, which is the
            // original behaviour and means the biggest single change this mod makes to the look
            // of the city is only reachable three quarters of the way through certain modes.
            spectacle.Set("blackoutWhen", JsonValue.Of("phase"));
            // Headlights too. Off keeps a blacked-out street readable rather than pitch black.
            spectacle.Set("blackoutVehicles", JsonValue.Of(false));
            // The grid coming back for half a second and going again.
            spectacle.Set("blackoutFlicker", JsonValue.Of(true));
            spectacle.Set("blackoutFlickerMs", JsonValue.Of(9000));
            spectacle.Set("barricades", JsonValue.Of(true));
            spectacle.Set("maxBarricades", JsonValue.Of(5));
            spectacle.Set("barricadeIntervalMs", JsonValue.Of(20000));
            spectacle.Set("barricadeRadius", JsonValue.Of(150));
            spectacle.Set("barricadeWidth", JsonValue.Of(5));
            spectacle.Set("burningBarricades", JsonValue.Of(true));
            spectacle.Set("burningChance", JsonValue.Of(0.7));
            spectacle.Set("smoke", JsonValue.Of(true));
            spectacle.Set("maxSmoke", JsonValue.Of(6));
            spectacle.Set("smokeScale", JsonValue.Of(6));
            // Particle assets stream like models. If the smoke never appears these are the two
            // values to change - they are community-documented names, not official ones.
            spectacle.Set("ptfxAsset", JsonValue.Of("core"));
            spectacle.Set("ptfxName", JsonValue.Of("exp_grd_bzgas_smoke"));
            features.Set("spectacle", spectacle);

            // Car chases. Provocation-driven: hurt someone and drive away, and their side
            // comes after you in a carload. Never touches the wanted system, so this can run
            // alongside a police or wanted overhaul without either noticing the other.
            JsonValue pursuit = JsonValue.NewObject();
            pursuit.Set("enabled", JsonValue.Of(true));
            // How long after you hurt someone their faction still wants to chase you.
            pursuit.Set("grudgeSeconds", JsonValue.Of(45));
            pursuit.Set("maxChases", JsonValue.Of(2));
            pursuit.Set("crewSize", JsonValue.Of(3));
            // "Tries to drive off" is the trigger, in metres per second. Sitting still in a
            // car should get you dragged out of it, not tailed.
            pursuit.Set("minPlayerSpeed", JsonValue.Of(6));
            pursuit.Set("formRadius", JsonValue.Of(120));
            pursuit.Set("gatherRadius", JsonValue.Of(35));
            pursuit.Set("vehicleSearchRadius", JsonValue.Of(45));
            // How long the crew gets to reach the car on foot before they are warped in. A
            // chase that never leaves the kerb is worse than one that starts a bit too neatly.
            pursuit.Set("boardTimeoutMs", JsonValue.Of(7000));
            pursuit.Set("cooldownMs", JsonValue.Of(12000));
            pursuit.Set("updateIntervalMs", JsonValue.Of(500));
            pursuit.Set("retaskMs", JsonValue.Of(5000));
            pursuit.Set("giveUpDistance", JsonValue.Of(320));
            pursuit.Set("giveUpSeconds", JsonValue.Of(12));
            pursuit.Set("maxSeconds", JsonValue.Of(150));
            pursuit.Set("driveBys", JsonValue.Of(true));
            pursuit.Set("driveByRange", JsonValue.Of(60));
            pursuit.Set("driveByAccuracy", JsonValue.Of(40));
            // Off: they tail you and shoot. On: they drive into you instead.
            pursuit.Set("ram", JsonValue.Of(false));
            pursuit.Set("aggressiveness", JsonValue.Of(1.0));
            pursuit.Set("driverAbility", JsonValue.Of(1.0));
            pursuit.Set("cruiseSpeed", JsonValue.Of(60));
            pursuit.Set("drivingStyle", JsonValue.Of(786603));
            pursuit.Set("blip", JsonValue.Of(true));
            pursuit.Set("notify", JsonValue.Of(true));
            features.Set("pursuit", pursuit);

            // Looting. Gated on the escalation phase, so it starts once the riot has been
            // going a while rather than in the first thirty seconds.
            JsonValue looting = JsonValue.NewObject();
            looting.Set("enabled", JsonValue.Of(true));
            looting.Set("maxActive", JsonValue.Of(6));
            looting.Set("intervalMs", JsonValue.Of(6000));
            looting.Set("radius", JsonValue.Of(90));
            looting.Set("jobSeconds", JsonValue.Of(40));
            looting.Set("runDistance", JsonValue.Of(70));
            looting.Set("carryProps", JsonValue.Of(true));
            // mixed | small. Small restricts looters to one-handed items - bags and cases -
            // for anyone who would rather nobody ran past holding a television.
            looting.Set("propStyle", JsonValue.Of("mixed"));
            // What can be carried and exactly how it sits in a hand. "box" items get both arms
            // and the box-carry animation; "hand" items hang off the prop bone in one.
            //
            // These offsets are eyeballed against models nobody documented, so they are config
            // rather than constants: a prop sitting wrong is an edit and a reload.
            looting.Set("props", CarryPropDefaults());
            // Fighters are busy. Looting is mostly what the people who were never going to
            // fight do instead, which is also what stops it thinning out the riot.
            looting.Set("fighterChance", JsonValue.Of(0.2));
            looting.Set("stealVehicles", JsonValue.Of(true));
            looting.Set("vehicleChance", JsonValue.Of(0.25));
            looting.Set("vehicleSearchRadius", JsonValue.Of(30));
            looting.Set("getawaySpeed", JsonValue.Of(25));
            looting.Set("drivingStyle", JsonValue.Of(786603));
            features.Set("looting", looting);

            // A faction that is losing sends more. Escalation phases answer "how long has this
            // been going on"; this answers "how badly is it going", which is the difference
            // between a deployment and a response.
            JsonValue reinforcements = JsonValue.NewObject();
            reinforcements.Set("enabled", JsonValue.Of(true));
            // Each spawned member killed adds this much to that faction's wave size, cap and
            // arrival rate. Sixteen losses reaches the ceiling at the default values.
            reinforcements.Set("perLoss", JsonValue.Of(0.06));
            reinforcements.Set("maxMultiplier", JsonValue.Of(2.5));
            reinforcements.Set("announce", JsonValue.Of(true));
            features.Set("reinforcements", reinforcements);

            // Ships in the sky. Props rather than vehicles, because GTA V's UFOs are props -
            // there is nothing to fly and nobody to put in one - so they are held at altitude
            // and drifted. A mode declares its own; only the invasion has any.
            JsonValue craft = JsonValue.NewObject();
            craft.Set("enabled", JsonValue.Of(true));
            craft.Set("maxActive", JsonValue.Of(4));
            craft.Set("orbitSpeed", JsonValue.Of(0.06));
            craft.Set("updateIntervalMs", JsonValue.Of(250));
            craft.Set("dropScatter", JsonValue.Of(20));
            craft.Set("blip", JsonValue.Of(true));
            // Formation geometry. Every ship owns one share of the orbit, one lane and one
            // altitude band, which is what stops a fleet flying through itself.
            craft.Set("radiusSpread", JsonValue.Of(25));
            craft.Set("heightSpread", JsonValue.Of(18));
            // The guarantee behind the plan: any two that do converge are pushed apart.
            craft.Set("minSeparation", JsonValue.Of(45));
            // How hard a ship is pulled towards where it should be, per second. Lower drifts
            // more lazily; 0 snaps, which is what the old fixed-step movement looked like.
            craft.Set("smoothing", JsonValue.Of(6));
            features.Set("craft", craft);

            // Whether the riot knows where you are.
            //
            // Off, hostility is a permanent property of a relationship group: every soldier in
            // the district is your enemy from the moment the mode starts, through walls and
            // around corners. On, being a target is a state you can get out of - break line of
            // sight, stay quiet, and they go back to fighting the people they can see.
            JsonValue perception = JsonValue.NewObject();
            perception.Set("enabled", JsonValue.Of(true));
            // Generous on purpose. The point of this feature is to stop them knowing where you
            // are through a wall, not to make them blind: at 60 the police spawned outside their
            // own sight range, drove the whole way in while the player read as unseen, and
            // arrived neutral - which is to say they did not shoot.
            perception.Set("sightRange", JsonValue.Of(140));
            // Inside this, line of sight is not asked. Somebody beside you knows you are there.
            perception.Set("closeRange", JsonValue.Of(30));
            // A car is loud and large, so it widens that.
            perception.Set("vehicleFactor", JsonValue.Of(1.8));
            // Flags for HAS_ENTITY_CLEAR_LOS_TO_ENTITY. 4 is the map only, so a car bonnet or a
            // bin does not count as concealment; 17 also counts vehicles and objects.
            perception.Set("losFlags", JsonValue.Of(4));
            // How long they keep looking after losing sight of you.
            perception.Set("forgetSeconds", JsonValue.Of(20));
            perception.Set("checkIntervalMs", JsonValue.Of(400));
            // Line-of-sight traces are the expensive part, so only this many per check. The
            // round-robin covers the whole crowd over a couple of seconds anyway.
            perception.Set("samplesPerCheck", JsonValue.Of(10));
            // Firing a weapon gives you away through walls, as it should.
            perception.Set("gunfireGivesYouAway", JsonValue.Of(true));
            // Crouching or taking cover multiplies their sight range by this.
            perception.Set("stealthFactor", JsonValue.Of(0.45));
            // On, a ped must be facing you to see you. Off by default: people have peripheral
            // vision, and a hard cone reads as the AI being broken rather than as stealth.
            perception.Set("requireFacing", JsonValue.Of(false));
            perception.Set("notify", JsonValue.Of(true));
            features.Set("perception", perception);

            JsonValue profiles = JsonValue.NewObject();
            profiles.Set("enabled", JsonValue.Of(true));
            profiles.Set("autoload", JsonValue.Of(""));
            features.Set("profiles", profiles);

            // Wave counting for modes that are only ever about you.
            JsonValue manhunt = JsonValue.NewObject();
            manhunt.Set("showWave", JsonValue.Of(true));
            manhunt.Set("killsPerWave", JsonValue.Of(6));
            features.Set("manhunt", manhunt);

            // A faction that grows by reaching people. Only Patient Zero uses it.
            JsonValue contagion = JsonValue.NewObject();
            contagion.Set("enabled", JsonValue.Of(true));
            features.Set("contagion", contagion);

            // One thing on the map that is coming for you specifically.
            //
            // Its real health is pinned and meaningless: damage is converted into a Resolve
            // pool at a fraction of its value, in whole while he is staggered, and staggering
            // him is a consequence of what he does rather than something you can force. Every
            // number below is part of that bargain, so changing one changes the fight.
            JsonValue hunter = JsonValue.NewObject();
            hunter.Set("enabled", JsonValue.Of(true));
            // The pool that actually has to be emptied. Raise it for a longer night.
            hunter.Set("resolve", JsonValue.Of(2400));
            hunter.Set("spawnDistance", JsonValue.Of(70));
            hunter.Set("weapon", JsonValue.Of("WEAPON_MACHETE"));
            hunter.Set("blip", JsonValue.Of(true));
            hunter.Set("showBar", JsonValue.Of(true));

            // What ordinary damage is worth, and what it is worth in the window.
            hunter.Set("armouredMultiplier", JsonValue.Of(0.2));
            hunter.Set("vulnerableMultiplier", JsonValue.Of(1.0));
            // A rocket, a car at speed, or whatever a physics mod just did to him. Always worth
            // more than its share, because a player who brought an RPG has earned an answer.
            hunter.Set("heavyHitThreshold", JsonValue.Of(150));
            hunter.Set("heavyHitMultiplier", JsonValue.Of(0.75));
            // Sustained fire is its own way in, for a player with no explosives and good aim.
            hunter.Set("breakThreshold", JsonValue.Of(900));
            hunter.Set("breakStaggerMs", JsonValue.Of(3000));
            hunter.Set("phaseStaggerMs", JsonValue.Of(4500));

            hunter.Set("moveRate", JsonValue.Of(1.55));
            hunter.Set("retaskMs", JsonValue.Of(1500));
            hunter.Set("meleeRange", JsonValue.Of(8));
            hunter.Set("strikeDamage", JsonValue.Of(45));
            // How often it can land one. Separate from the ability cooldowns: sharing them
            // meant a rush that connected could never actually hit anything, because the rush
            // had just pushed that timer six seconds into the future.
            hunter.Set("strikeIntervalMs", JsonValue.Of(1500));
            hunter.Set("vehicleDamage", JsonValue.Of(260));
            hunter.Set("flightSpeed", JsonValue.Of(26));
            hunter.Set("leashDistance", JsonValue.Of(220));
            hunter.Set("nearDistance", JsonValue.Of(25));
            hunter.Set("trailChance", JsonValue.Of(0.5));
            hunter.Set("timeSlow", JsonValue.Of(true));

            hunter.Set("rushRange", JsonValue.Of(55));
            hunter.Set("rushSpeed", JsonValue.Of(42));
            hunter.Set("rushMs", JsonValue.Of(1400));
            hunter.Set("rushCooldownMs", JsonValue.Of(6500));
            hunter.Set("rushRecoveryMs", JsonValue.Of(1600));

            hunter.Set("blinkMs", JsonValue.Of(700));
            hunter.Set("blinkCooldownMs", JsonValue.Of(9000));
            hunter.Set("blinkArrivalRange", JsonValue.Of(22));

            hunter.Set("slamRange", JsonValue.Of(9));
            hunter.Set("slamRadius", JsonValue.Of(12));
            hunter.Set("slamDamage", JsonValue.Of(30));
            hunter.Set("slamCooldownMs", JsonValue.Of(8000));
            hunter.Set("slamRecoveryMs", JsonValue.Of(3200));

            hunter.Set("cull", JsonValue.Of(true));
            hunter.Set("cullIntervalMs", JsonValue.Of(2500));
            hunter.Set("cullRadius", JsonValue.Of(5));

            // Particle assets, screen effects and an explosion id, all community-documented
            // rather than official. Written as "asset/effect". Anything missing is skipped: a
            // hunter with no particles is still a hunter.
            JsonValue hunterFx = JsonValue.NewObject();
            hunterFx.Set("trail", JsonValue.Of("core/exp_grd_bzgas_smoke"));
            hunterFx.Set("blink", JsonValue.Of("core/exp_grd_bzgas_smoke"));
            hunterFx.Set("slam", JsonValue.Of("core/exp_grd_bzgas_smoke"));
            hunterFx.Set("nearEffect", JsonValue.Of("RaceTurbo"));
            hunterFx.Set("phaseEffect", JsonValue.Of("DrugsTrevorClownsFightIn"));
            hunterFx.Set("deathEffect", JsonValue.Of("SwitchHUDIn"));
            // 4 is a rocket. Raised with zero damage and no visible effect: the shockwave is
            // for the shove, and every point of damage he does is applied by hand.
            hunterFx.Set("slamExplosion", JsonValue.Of(4));
            hunter.Set("fx", hunterFx);

            features.Set("hunter", hunter);

            root.Set("features", features);
            return root;
        }
    }
}
